USE [Enterprise]
GO

/****** Object:  Table [dbo].[PayrollEmployees]    Script Date: 9/27/2018 12:18:04 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PayrollEmployees](
	[CompanyID] [nvarchar](36) NOT NULL,
	[DivisionID] [nvarchar](36) NOT NULL,
	[DepartmentID] [nvarchar](36) NOT NULL,
	[EmployeeID] [nvarchar](36) NOT NULL,
	[EmployeeTypeID] [nvarchar](36) NULL,
	[EmployeeUserName] [nvarchar](36) NULL,
	[EmployeePassword] [nvarchar](15) NULL CONSTRAINT [DF_PayrollEmployees_EmployeePassword]  DEFAULT (N';jE'),
	[EmployeePasswordOld] [nvarchar](15) NULL,
	[EmployeePasswordDate] [datetime] NULL,
	[EmployeePasswordExpires] [bit] NULL,
	[EmployeePasswordExpiresDate] [int] NULL,
	[EmployeeName] [nvarchar](50) NULL,
	[ActiveYN] [bit] NULL CONSTRAINT [DF_PayrollEmployees_ActiveYN]  DEFAULT ((1)),
	[EmployeeAddress1] [nvarchar](50) NULL,
	[EmployeeAddress2] [nvarchar](50) NULL,
	[EmployeeCity] [nvarchar](50) NULL,
	[EmployeeState] [nvarchar](50) NULL,
	[EmployeeZip] [nvarchar](36) NULL,
	[EmployeeCountry] [nvarchar](50) NULL,
	[EmployeePhone] [nvarchar](30) NULL,
	[EmployeeFax] [nvarchar](30) NULL,
	[EmployeeSSNumber] [nvarchar](15) NULL,
	[EmployeeEmailAddress] [nvarchar](60) NULL,
	[EmployeeDepartmentID] [nvarchar](36) NULL,
	[PictureURL] [nvarchar](80) NULL,
	[HireDate] [datetime] NULL,
	[Birthday] [datetime] NULL,
	[Commissionable] [bit] NULL CONSTRAINT [DF_PayrollEmployees_Commissionable]  DEFAULT ((1)),
	[CommissionPerc] [float] NULL,
	[CommissionCalcMethod] [nvarchar](1) NULL,
	[EmployeeManager] [nvarchar](36) NULL,
	[EmployeeRegionID] [nvarchar](36) NULL,
	[EmployeeSourceID] [nvarchar](36) NULL,
	[EmployeeIndustryID] [nvarchar](36) NULL,
	[Notes] [nvarchar](255) NULL,
	[NextOfKinName] [nvarchar](50) NULL,
	[NextOfKinNumber] [nvarchar](30) NULL,
	[MonthToDateGross] [money] NULL,
	[MonthToDateFICA] [money] NULL,
	[MonthToDateFederal] [money] NULL,
	[MonthToDateState] [money] NULL,
	[MonthToDateLocal] [money] NULL,
	[MonthToDateOther] [money] NULL,
	[QuarterToDateGross] [money] NULL,
	[QuarterToDateFICA] [money] NULL,
	[QuarterToDateFederal] [money] NULL,
	[QuarterToDateState] [money] NULL,
	[QuarterToDateLocal] [money] NULL,
	[QuarterToDateOther] [money] NULL,
	[YearToDateGross] [money] NULL,
	[YearToDateFICA] [money] NULL,
	[YearToDateFederal] [money] NULL,
	[YearToDateState] [money] NULL,
	[YearToDateLocal] [money] NULL,
	[YearToDateOther] [money] NULL,
	[EmployeeCounty] [nvarchar](50) NULL,
	[Approved] [bit] NULL,
	[ApprovedBy] [nvarchar](36) NULL,
	[ApprovedDate] [datetime] NULL,
	[EnteredBy] [nvarchar](36) NULL,
	[LockedBy] [nvarchar](36) NULL,
	[LockTS] [datetime] NULL,
	[LastEditDate] [datetime] NULL CONSTRAINT [DF_PayrollEmployees_LastEditDate]  DEFAULT (getutcdate()),
	[CreationDate] [datetime] NULL CONSTRAINT [DF_PayrollEmployees_CreationDate]  DEFAULT (getutcdate()),
	[DocumentID] [nvarchar](36) NULL CONSTRAINT [DF_PayrollEmployees_DocumentID]  DEFAULT (N'DEFAULT'),
	[EmployeeFirstname] [nvarchar](50) NULL,
	[EmployeeOthername] [nvarchar](50) NULL,
	[TitleID] [nvarchar](36) NULL CONSTRAINT [DF_PayrollEmployees_TitleID]  DEFAULT (N'DEFAULT'),
	[EmployeeHomephone] [nvarchar](36) NULL,
	[EmployeeOfficephone] [nvarchar](36) NULL,
	[EmployeeOfficeExt] [nvarchar](36) NULL,
	[EmployeeAddress3] [nvarchar](50) NULL,
	[EmployeeAddress4] [nvarchar](50) NULL,
	[EmployeeAddress5] [nvarchar](50) NULL,
	[PFAID] [nvarchar](36) NULL CONSTRAINT [DF_PayrollEmployees_PFAID]  DEFAULT (N'DEFAULT'),
	[BankID] [nvarchar](36) NULL CONSTRAINT [DF_PayrollEmployees_BankID]  DEFAULT (N'DEFAULT'),
	[DesignationID] [nvarchar](36) NULL CONSTRAINT [DF_PayrollEmployees_DesignationID]  DEFAULT (N'DEFAULT'),
	[EmployeeManagerID] [nvarchar](36) NULL CONSTRAINT [DF_PayrollEmployees_EmployeeManagerID]  DEFAULT (N'DEFAULT'),
	[ContractTypeID] [nvarchar](36) NULL CONSTRAINT [DF_PayrollEmployees_ContractTypeID]  DEFAULT (N'DEFAULT'),
	[CurrencyID] [nvarchar](36) NULL CONSTRAINT [DF_PayrollEmployees_CurrencyID]  DEFAULT (N'NGN'),
	[EmployeeMaidenName] [nvarchar](50) NULL,
	[Disabled] [bit] NULL,
	[PFANo] [nvarchar](36) NULL,
	[GenderID] [nvarchar](36) NULL,
	[StatusID] [nvarchar](36) NULL,
	[StateID] [nvarchar](36) NULL,
	[NationalityID] [nvarchar](36) NULL,
	[LanguageID] [nvarchar](36) NULL,
	[GradeID] [nvarchar](36) NULL,
	[AccountNo] [nvarchar](36) NULL,
	[GroupID] [nvarchar](36) NULL,
	[Taxable] [bit] NULL CONSTRAINT [DF_PayrollEmployees_Taxable]  DEFAULT ((1)),
	[JobClassID] [nvarchar](36) NULL,
	[Location] [nvarchar](36) NULL,
	[CostCenter] [nvarchar](36) NULL,
	[BaseValue] [float] NULL,
	[MonthlyTax] [float] NULL,
	[YearToDateTax] [float] NULL,
	[Department] [nvarchar](36) NULL,
	[PromotionDate] [datetime] NULL,
	[WorkedDays] [nvarchar](36) NULL,
	[LastPayDate] [datetime] NULL,
	[PensionDate] [datetime] NULL,
	[StatePAYE] [nvarchar](36) NULL,
	[Gross] [money] NULL,
	[ConfirmationDate] [datetime] NULL,
	[GroupDescription] [nvarchar](36) NULL,
	[Picture] [varbinary](max) NULL,
	[Cleared] [bit] NULL,
	[EmployeeActivityTypeID] [nvarchar](36) NULL,
	[ProvideForTax] [bit] NULL,
	[PayrollEmployeeUserGroupID] [nvarchar](36) NULL,
	[EmployeePostalAddress] [nvarchar](50) NULL,
	[LGA] [nvarchar](36) NULL,
	[GeoArea] [nvarchar](36) NULL,
	[BnkSortCode] [int] NULL,
	[Tax_Number] [nvarchar](36) NULL,
 CONSTRAINT [pk_PayrollEmployees] PRIMARY KEY NONCLUSTERED 
(
	[CompanyID] ASC,
	[DivisionID] ASC,
	[DepartmentID] ASC,
	[EmployeeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


